name: sampling_theorem
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  share_plus: ^12.0.1
  speech_to_text: ^7.3.0
  shared_preferences: ^2.5.3
  record: ^6.1.2
  # flutter_sound: ^9.30.0
  # just_audio: ^0.10.5
  audio_waveforms: ^2.0.1
  # mic_stream: ^0.7.2
  permission_handler: ^12.0.1
  # flutter_sound_platform_interface: ^9.30.0
  path_provider: ^2.1.5
  path: ^1.9.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
